name: Release expressapp with Docker
on:
  push:
    branches:
      - main

jobs:
  publish-docker-hub:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    # checkout
    - name: Checkout
      uses: actions/checkout@v3

    # login
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Building and pushing
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: jormakemppainen/expressapp:latest
